version: '3.7'

services:
  email-service:
    image: microservice-email
    build:
      context: microservice-email
      dockerfile: cmd/microservice-email/Dockerfile
    container_name: animals_email_service
    hostname: microservice_email
    ports:
      - "127.0.0.1:8084:8080"
    volumes:
      - ./microservice-emaile:/code
    environment:
      - PORT=8080
      - CONF_FILE=microservice-email.conf
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
     
volumes: 
  redis-persistence:
    driver: local
  mongodb-persistence: